### ISSUE TITLE
Prevent user from instancing a scene into itself

### ISSUE THREAD

**Issue by ghost** [willnationsdev/godot-inheritance-dock#1]
Plugin version 265a971
Godot version https://github.com/godotengine/godot/commit/7f1265b41fc52def42c433e5d324070bc6454d6b

**Issue description:**
Instancing scene into itself will cause runtime error. The editor tries to prevent this.
https://youtu.be/o5ar5r3TW0Q?t=46s

**Steps to reproduce:**
1. New Node, save scene, select that node in the Scene dock.
2. Select newly created scene from the inheritance dock and instance it.
3. Run the scene

Thank you for this very nice plugin! Hope it can be integrated to the editor dependencies dialog. :)

**Comment by willnationsdev** [comment]
I guess what I can do here is edit the EditorPlugin's `_on_instance_scene_request` connection and have it double check that it isn't doing a circular thing. And if it does, create an Error popup to notify the user...

**Comment by willnationsdev** [comment]
Fixed with dc0e433
